### ISSUE TITLE
Breaks reordering songs in Play Queue

### ISSUE THREAD

**Issue by nachokb** [fossfreedom/alternative-toolbar#86]
When this plugin is enabled, you can't reorder songs anymore. It works disabling this plugin.

Like this: https://youtu.be/xt2QadSdMeA
##

**Comment by aquatix** [comment]
Same issue here, it's a tad bothersome :)

**Comment by fossfreedom** [comment]
hopefully fixed by the above

**Comment by nachokb** [comment]
@fossfreedom I upgraded to 3.4 and it's still happening, but I can't see if that commit is in there or not (how do you track that? tags?)

Thanks for this plugin btw! Do you know whether upstream is interested in integrating this?

**Comment by fossfreedom** [comment]
I haven't tagged a release, but it should be fixed in master.

Upstream were not interested. They were looking for a native Client based patch, not a python plugin.
